//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
        public Nullable<int> room { get; set; }
    
        public virtual PHONGBAN PHONGBAN { get; set; }
        public virtual SalaryStaff SalaryStaff { get; set; }
    }
}
