//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryStaff
    {
        public int Id { get; set; }
        public double salary { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
    }
}
